RCF/core/urls.py
from django.contrib import admin
from django.urls import path, include

from RCF.core import views
app_name = "reader"
urlpatterns = [
	path('user/', views.showmainmenu, name='user'),
	path('', views.readexcel,name='readexcel'),
	path('', views.showpastorder, name='demo'),
	path('', views.readexcel2, name='readexcel2'),
]

RCF/urls.py
#from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
#from django.contrib.auth import views as auth_views
from RCF.core import views
from RCF.core.views import PersonListView, showpastorder
from RCF.core.views import demo
from RCF.core import views as views2

urlpatterns = [
	path('', views.home, name='home'),
	path('user/', views.showpastorder, name='user'),
	#path('ordernowsubmission/', views.ordernowsubmission, name='ordernowsubmission'),
	path('myadmin/', views.adminlogin, name='loginpage'),
	path('menupage/', views.showmainmenu, name='menupage'),
	path('adminpage/', views.Insertrecord, name='adminpage'),
	path('',views.showmenu),
	path('signup/', views.register_view, name='signup'),
	path('login/', views.login_view, name='login'),
	#path('myadmin/', views.demo, name='demo'),
	path('myadmin/demo/', include('RCF.core.urls',namespace="reader_name")),
	path('myadmin/demo/', include('RCF.core.urls',namespace="reader_name2")),
	path('Delete/<int:id>',views.delrec),
	path('', views.showsociety),
	path('', PersonListView.as_view()),
	path('accounts/', include('django.contrib.auth.urls')),
   	path('admin/', admin.site.urls),
   	path('', views.showmainmenu),
   	#path('showorder/',views.showorder),
   #path('adminpage/templates/index.html/', views.save_alacarta, name='index'),
   path('',views.offtiffdisplay),
   path('adminpage/templates/index.html/',views.save_all, name='index'),
   path('', include('RCF.core.urls')),
  path('', views.insertalacarta),
  path('contact/',views.Contact, name='contact'),

]

RCF/core/forms.py
from django import forms
from django.contrib.auth import login,authenticate, get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from RCF.core.models import societyname


USER_TYPE_CHOICES = (
('school', 'School Tiffin'),
('office', 'Office Tiffin'),)


class RF(UserCreationForm):
	society=forms.CharField(required=True)
	confirm_password=forms.CharField(required=True)

	class Meta:
		model=User
		fields = (
			"username",
			"email",
			"password",
			"confirm_password",
			"society",
		)
	def save(self,commit=True):
		user=super(RF, self).save(commit=False)
		user.society=self.cleaned_data.get('society')

		if commit:
			user.save()
		return user


User = get_user_model()

class RegisterForm(forms.ModelForm):
	society=forms.CharField(required=True)
	class Meta:
		model = User
		fields = [
			"username",
			"email",
			"password",
			"confirm_password", 
			"society",
		]
	username = forms.CharField()
	email = forms.EmailField(label = "Email")
	password = forms.CharField(widget = forms.PasswordInput)
	confirm_password = forms.CharField(widget = forms.PasswordInput)
	society = forms.ModelChoiceField(queryset= societyname.objects.all(), label = "Select your Society")


	def __init__(self, *args, **kwargs):
		super(RegisterForm, self).__init__(*args, **kwargs)
		self.fields['username'].widget.attrs.update({
		    'class': 'form-control',
		    "name":"username"})
		self.fields['email'].widget.attrs.update({
		    'class': 'form-control',
		    "name":"email"})
		self.fields['society'].widget.attrs.update({
		    'class': 'form-control',
		    "name":"society"})
		self.fields['confirm_password'].widget.attrs.update({
		    'class': 'form-control',
		    "name":"confirm_password"})
		self.fields['password'].widget.attrs.update({
		    'class': 'form-control',
		    "name":"password"})
		


	def clean(self, *args, **keyargs):
		email = self.cleaned_data.get("email")
		confirm_password = self.cleaned_data.get("confirm_password")
		username = self.cleaned_data.get("username")
		password = self.cleaned_data.get("password")
		society = self.cleaned_data.get("society")

		if password != confirm_password:
			raise forms.ValidationError("Passwords do not match")
		
		email_qs = User.objects.filter(email=email)
		if email_qs.exists():
			raise forms.ValidationError("Email is already registered")

		username_qs = User.objects.filter(username=username)
		if username_qs.exists():
			raise forms.ValidationError("User with this username already registered")
		
		#you can add more validations for password

		if len(password) < 8:	
			raise forms.ValidationError("Password must be greater than 8 characters")


		return super(RegisterForm, self).clean(*args, **keyargs)



class UsersLoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget = forms.PasswordInput,)

	def __init__(self, *args, **kwargs):
		super(UsersLoginForm, self).__init__(*args, **kwargs)
		self.fields['username'].widget.attrs.update({
		    'class': 'form-control',
		    "name":"username"})
		self.fields['password'].widget.attrs.update({
		    'class': 'form-control',
		    "name":"password"})

	def clean(self, *args, **keyargs):
		username = self.cleaned_data.get("username")
		password = self.cleaned_data.get("password")

		if username and password:
			user = authenticate(username = username, password = password)
			if not user:
				raise forms.ValidationError("This user does not exists")
			if not user.check_password(password):
				raise forms.ValidationError("Incorrect Password")
			if not user.is_active:
				raise forms.ValidationError("User is no longer active")

		return super(UsersLoginForm, self).clean(*args, **keyargs)


class AdminLoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget = forms.PasswordInput,)

	def __init__(self, *args, **kwargs):
		super(AdminLoginForm, self).__init__(*args, **kwargs)
		self.fields['username'].widget.attrs.update({
		    'class': 'form-control',
		    "name":"username"})
		self.fields['password'].widget.attrs.update({
		    'class': 'form-control',
		    "name":"password"})

	def clean(self, *args, **keyargs):
		username = self.cleaned_data.get("username")
		password = self.cleaned_data.get("password")

		if username and password:
			user = authenticate(username = username, password = password)
			if not user:
				raise forms.ValidationError("This user does not exists")
			if not user.check_password(password):
				raise forms.ValidationError("Incorrect Password")
			if not user.is_active:
				raise forms.ValidationError("User is no longer active")

		return super(AdminLoginForm, self).clean(*args, **keyargs)



class ContactForm(forms.Form):
    contact_name= forms.CharField(max_length=500, label="Name")
    contact_email= forms.EmailField(max_length=500, label="Email", required=True)
    content= forms.CharField(label='',widget=forms.Textarea(attrs={'placeholder': 'Enter your comments here'}))

RCF/core/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.views.generic import CreateView
from .forms import RegisterForm
#from .models import RegistrationData
from django.contrib import messages
from django.shortcuts import get_list_or_404, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from .forms import UsersLoginForm, AdminLoginForm
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from RCF.core.forms import RegisterForm, ContactForm
from RCF.core.models import EmpInsert, EmpInsert2, carta, carorder, orderdisplay, OrderNow, menudisplay, otdisplay, ltdisplay, dtdisplay, alacartaorder
from django.views.generic import ListView
from django.template import RequestContext
from django.core.mail import send_mail
from django.conf import settings
from django.template.loader import get_template
from django.core.mail import EmailMessage
import openpyxl
from datetime import date
from django.template.loader import render_to_string

from django.contrib.auth.models import User


def save_all(request):
	if request.method=='POST':
	
		post=carorder()
		post.carid= request.POST.get('carid')
		post.carmenu= request.POST.get('carmenu')
		post.carqty= request.POST.get('carqty')
		post.caramt=request.POST.get('caramt')
		post.author=request.user
		post.save()
		messages.success(request, "Order placed Successfully!!")
		return render(request, 'index.html')  

	else:
		res1=alacartaorder.objects.all()
		return render(request, 'index.html', {'alacartaorder':res1})

	return render(request,'adminpage.html')





def Insertrecord(request):

	if request.method=='POST':
		username=None
		saverecord=OrderNow()
		saverecord.ordernow_id=request.POST.get('ordernow_id')
		saverecord.tiffin_type=request.POST.get('tiffin_type')
		saverecord.subtiffin_type=request.POST.get('subtiffin_type')
		saverecord.from_date=request.POST.get('from_date')
		saverecord.to_date=request.POST.get('to_date')
		saverecord.total_amount=request.POST.get('total_amount')
		if request.user.is_authenticated:
			saverecord.author=request.user
			#saverecord.email=request.user
		#if request.user.is_authenticated:
			#author=request.user.username
		saverecord.save()
		
		#messages.success(request, "Order Placed Succesfully")
		return render(request, 'user.html')
	else:
		res1=carta.objects.all()
		return render(request, 'adminpage.html', {'carta':res1})


@login_required
def insertalacarta(request):
	if request.method=='POST':
		saverecord=alacartaorder()
		saverecord.aid=request.POST.get('aid')
		saverecord.amenu=request.POST.get('amenu')
		saverecord.aamount=request.POST.get('aamount')
		
		
		saverecord.save()
		
		#messages.success(request, 'Order Placed successfully!!..')
		return render(request, 'user.html')
	else:
		res1=carta.objects.all()
		res2=alacartaorder.objects.all()
		return render(request, 'adminpage.html', {'carta':res1, 'alacartaorder':res2})


def showsociety(request):
	results=showsoc.objects.all()
	return render(request, "signup.html", {"results":results})

def showmenu(request):
	r1=carta.objects.all()
	return render(request, "adminpage.html", {"carta":r1})

def showpastorder(request):
	res=OrderNow.objects.filter(author_id=request.user)
	return render(request, "user.html", {'OrderNow':res})


def showpastorder1(request):
	res=OrderNow.objects.all()
	
	return render(request, "base.html", {'OrderNow':res})
@login_required
def showmainmenu(request):
	result1=menudisplay.objects.all()
	result2=otdisplay.objects.all()
	result3=ltdisplay.objects.all()
	result4=dtdisplay.objects.all()
	return render(request, "menupage.html", {'menudisplay':result1, 'otdisplay':result2, 'ltdisplay':result3, 'dtdisplay':result4})
def offtiffdisplay(request):
	result1=otdisplay.objects.all()
	return render(request, "menupage.html", {'otdisplay':result1})

@login_required
def index(request):
    return render(request,'user.html')

def odnow(request):
	return render(request, 'ordernow.html')

def home(request):
	return render(request, 'home.html')


def signup(request):
	
	
	return render(request, 'registration/signup.html',context)





def register_view(request):
	form = RegisterForm(request.POST or None)
	#profile_form=UserProfileForm(request.POST or None)
	if form.is_valid():
		user = form.save()
		#profile=profile_form.save(commit=False)
		#profile.user=user
		#profile.save()
		
		username=form.cleaned_data.get("username")
		password = form.cleaned_data.get("password")
		society=form.cleaned_data.get("society")
		user.set_password(password)
		#user.set_society(society)
		user.save()
		
		messages.success(request, 'Account Registered Successfully!!')
		form=RegisterForm()
		#profile_form=UserProfileForm()

	context = {"form":RegisterForm}
	return render(request, "registration/signup.html", {
		"title" : "Register",
		"form" : form,
	})


@login_required
def login_view(request):
	form = UsersLoginForm(request.POST or None)
	
	if form.is_valid():
		username = form.cleaned_data.get("username")
		password = form.cleaned_data.get("password")
		user = authenticate(username = username, password = password)
		if request.user.is_superuser:
			login(request, user)
			return render(request, 'support.html')
	else:
		return render(request, 'user.html')


@login_required
def adminlogin(request):
	form = AdminLoginForm(request.POST or None)
	
	if form.is_valid():
		username = form.cleaned_data.get("username")
		password = form.cleaned_data.get("password")
		user = authenticate(username = username, password = password)
		if request.user.is_superuser:
			login(request, user)
			#messages.messages.success("New account created")
			return HttpResponseRedirect("")
	else:
		res1=OrderNow.objects.all()
		return render(request, 'adminhome.html',{'OrderNow':res1})
		


@login_required
def user(request):
    return render(request, 'user.html')
def menupage(request):
    return render(request, 'menupage.html')
def adminpage(request):

    return render(request, 'adminpage.html')
def support(request):
	form = AdminLoginForm(request.POST or None)
	
	if form.is_valid():
		username = form.cleaned_data.get("username")
		password = form.cleaned_data.get("password")
		user = authenticate(username = username, password = password)
		if request.user.is_superuser:
			login(request, user)
			messages.messages.success("New account created")
			return render(request, 'demo.html')
	else:
    		return render(request, 'support.html')
def index(request):
    return render(request, 'index.html')


def showorder(request):

	return render_to_response('user.html', {'obj': models.OrderNow.objects.all()})

class PersonListView(ListView):
    model = EmpInsert2
    template_name = 'user.html'

def demo(request):
	result= OrderNow.objects.all()
	return render(request, 'adminhome.html', {'OrderNow':result})


def user_login(request):
	context = RequestContext(request)
	if request.method == 'POST':
		username = request.POST.get('username',False)
		password = request.POST.get('password',False)
		user = authenticate(username=username, password=password)
		if user is not None and user.is_superuser:
			login(request, user)
			return HttpResponseRedirect("myadmin")
	else:
		return render(request, 'adminhome.html')


def Contact(request):
	
	if request.method=='POST':
		name = request.POST.get('name')
		email = request.POST.get('email')
		message = request.POST.get('message')
		context= {'name':name, 'email':email, 'message':message}

		template=render_to_string('contact_form.txt',context)
		send_mail('Contact Form',
			template,
			settings.EMAIL_HOST_USER,
			['amitrajput111777@gmail.com'],
			fail_silently=False)

	return render(request, 'contact.html')



def readexcel(request):
	if "GET" == request.method:
		return render(request, 'adminhome.html')
	else:
		excel_file=request.FILES["excel_file"]

	#You may put the file extension check here
	wb=openpyxl.load_workbook(excel_file)

	# getting all sheets
	sheets = wb.sheetnames
	#print(sheets)

	#getting a particular sheet by name
	#Read School Worksheet
	schoolworksheet = wb["School Tiffin"]
	#print(schoolworksheet)

	#excel_data=list()
	#Iterate and get values from each cell
	menu_display=menudisplay()
	for rowno, rowval in enumerate(schoolworksheet.iter_rows(min_row=2, max_row=schoolworksheet.max_row),start=2):
		
		
		menu_display.mdate=schoolworksheet.cell(row=rowno,column=1).value
		menu_display.Vegetarian=(schoolworksheet.cell(row=rowno,column=2).value)
		menu_display.Mixed=(schoolworksheet.cell(row=rowno,column=3).value)
		menu_display.Premium_Veg=(schoolworksheet.cell(row=rowno,column=4).value)
		menu_display.Premium_Mixed=(schoolworksheet.cell(row=rowno,column=5).value)
		menu_display.save()


	officeworksheet = wb["Office Tiffin"]

	office_display=otdisplay()
	for rowno, rowval in enumerate(officeworksheet.iter_rows(min_row=2, max_row=officeworksheet.max_row),start=2):
		
		office_display.odate1=officeworksheet.cell(row=rowno,column=1).value
		office_display.Vegetarian1=(officeworksheet.cell(row=rowno,column=2).value)
		office_display.Mixed1=(officeworksheet.cell(row=rowno,column=3).value)
		office_display.Premium_Veg1=(officeworksheet.cell(row=rowno,column=4).value)
		office_display.Premium_Mixed1=(officeworksheet.cell(row=rowno,column=5).value)
		office_display.save()
	
	lunchworksheet = wb["Lunch Tiffin"]
	lunch_display=ltdisplay()
	for rowno, rowval in enumerate(lunchworksheet.iter_rows(min_row=2, max_row=lunchworksheet.max_row),start=2):
		
		lunch_display.ldate=lunchworksheet.cell(row=rowno,column=1).value
		lunch_display.Vegetarian=(lunchworksheet.cell(row=rowno,column=2).value)
		lunch_display.Mixed=(lunchworksheet.cell(row=rowno,column=3).value)
		lunch_display.Premium_Veg=(lunchworksheet.cell(row=rowno,column=4).value)
		lunch_display.Premium_Mixed=(lunchworksheet.cell(row=rowno,column=5).value)
		lunch_display.save()


	dinnerworksheet = wb["Dinner Tiffin"]
	dinner_display=dtdisplay()

RCF/templates/adminhome.html
{% block content %}
{% csrf_token %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Chapati Roti Factory</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  <script type="text/javascript">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  
  	
  </script>
  <script>

$(document).ready(function(){  
           $('#search').keyup(function(){  
                search_table($(this).val());  
           });  
           function search_table(value){  
                $('#data tr').each(function(){  
                     var found = 'false';  
                     $(this).each(function(){  
                          if($(this).text().toLowerCase().indexOf(value.toLowerCase()) >= 0)  
                          {  
                               found = 'true';  
                          }  
                     });  
                     if(found == 'true')  
                     {  
                          $(this).show();  
                     }  
                     else  
                     {  
                          $(this).hide();  
                     }  
                });  
           }  
      });





   $(document).ready(function(){
    $('#data').after('<div id="nav"></div>');
    var rowsShown = 10;
    var rowsTotal = $('#data tbody tr').length;
    var numPages = rowsTotal/rowsShown;
    for(i = 0;i < numPages;i++) {
        var pageNum = i + 1;
        $('#nav').append('<a href="#" rel="'+i+'">'+pageNum+'</a> ');
    }
    $('#data tbody tr').hide();
    $('#data tbody tr').slice(0, rowsShown).show();
    $('#nav a:first').addClass('active');
    $('#nav a').bind('click', function(){

        $('#nav a').removeClass('active');
        $(this).addClass('active');
        var currPage = $(this).attr('rel');
        var startItem = currPage * rowsShown;
        var endItem = startItem + rowsShown;
        $('#data tbody tr').css('opacity','0.0').hide().slice(startItem, endItem).
        css('display','table-row').animate({opacity:1}, 300);
    });
});

  function downloadCSV(csv, filename) {
    var csvFile;
    var downloadLink;

    // CSV file
    csvFile = new Blob([csv], {type: "text/csv"});

    // Download link
    downloadLink = document.createElement("a");

    // File name
    downloadLink.download = filename;

    // Create a link to the file
    downloadLink.href = window.URL.createObjectURL(csvFile);

    // Hide download link
    downloadLink.style.display = "none";

    // Add the link to DOM
    document.body.appendChild(downloadLink);

    // Click download link
    downloadLink.click();
}
function exportTableToCSV(filename) {
    var csv = [];
    var rows = document.querySelectorAll("table tr");
    
    for (var i = 0; i < rows.length; i++) {
        var row = [], cols = rows[i].querySelectorAll("td, th");
        
        for (var j = 0; j < cols.length; j++) 
            row.push(cols[j].innerText);
        
        csv.push(row.join(","));        
    }

    // Download CSV file
    downloadCSV(csv.join("\n"), filename);
}


  </script>
</head>
<style>
.sections {display:none;}
.sections:target {display:block;}
}

#navbar li {
  display: inline;
  [COLOR="Red"]padding-right: 30px;[/COLOR]
}
body{
  background-color:white;
}
</style>
<body>
<nav class="navbar navbar-expand-sm"style="background-color: #7aba1e;">
  {% load static %}
 <img src="{% static 'images/header2.jpeg' %}" href="{% url 'home' %}"style="height:80px;">
  
  
  <!-- Links -->
  <ul class="navbar-nav">
     <li class="home"style="padding:10px"><a href="#1"style="padding:10px;text-transform:uppercase;color:#fff">Upload Menu</a></li>
     <li class="overview"style="padding:10px"><a href="#2"style="padding:10px;text-transform:uppercase;color:#fff">Upload A-La-Carta Menu</a></li>
     <li class="reports"style="padding:10px"><a href="#3"style="padding:10px;text-transform:uppercase;color:#fff">Reports</a></li>
     <li class="logout" style="padding:10px"><a href="{% url 'logout' %}" style="padding:10px;text-transform:uppercase;color:red">Logout</a></li>
  </ul>

</nav>
<br>
<br>

<form action="{% url 'reader_name:readexcel' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
<div class="container">
	<div class="d1" id="1">
	<p> This will upload the monthly menu for all tiffins like School Tiffin, Office Tiffin, Lunch Tiffin and Dinner Tiffin</p>
  {% for row in excel_data %}
            {% for cell in row %}
                {{ cell }}&nbsp;&nbsp;
            {% endfor %}
            <br>
        {% endfor %}  
  <div class="file-upload-wrapper">
  Select a file to upload: <input type="file" id="input-file-now" class="file-upload" name="excel_file" />
  <input type="submit" value="submit"/>
	</div>
</div>
</form>

	


	<!-- 2nd DIV -->
<form action="{% url 'reader_name2:readexcel2' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
	<div class="d2" id="2">
	<p> This will upload the monthly menu A-La-Carta Tiffin</p>
  {% for row in excel_data %}
            {% for cell in row %}
                {{ cell }}&nbsp;&nbsp;
            {% endfor %}
            <br>
        {% endfor %}  
  <div class="file-upload-wrapper">
  Select a file to upload: <input type="file" id="input-file-now" class="file-upload" name="excel_file2" />
  <input type="submit" value="submit"/>
	</div>
	</div>
</form>
	<!-- 3rd DIV -->
</form>







	<div class="d3" id="3">
    
    

<input type="text" id="search" placeholder="  live search" onkeyup="sumtot()"></input>

  
    
		<button onclick="exportTableToCSV('OrderReport.csv')">Export To Excel</button>
    <br>
	<table border="1" class="table" id="data" style="width:70rem;background-color: white">
                <tbody>
                    <tr class="filters"style="background-color: yellow">
                      <th>Order ID</th>
                      <th>Tiffin Type</th>
                      <th>SubTiffin Type</th>
                      <th>From</th>
                      <th>To</th>
                      <th>Amount</th>
                      <th>Ordered By</th>


                    </tr>
                    {% for getdata in OrderNow%}
                    <tr>
                        <td>{{getdata.ordernow_id}}</td>
                        <td>{{getdata.tiffin_type}}</td>
                        <td>{{getdata.subtiffin_type}}</td>
                        <td>{{getdata.from_date}}</td>
                        <td>{{getdata.to_date}}</td>
                        <td>{{getdata.total_amount}}</td>
                        <td>{{getdata.author_id}}</td>
                        

                    </tr>
                   {% endfor%}
               </tbody>
    </table>
    
    <br />
    Total Amount Rs:
    <input type="text" name="name" id="txtSum" disabled="true"/>
	</div>


</div>
<script type="text/javascript">
$("#search").on("keyup", function() {
    var value = $("#data").val();

    $("table tr").each(function(index) {
        if (index !== 0) {

            $row = $(this);

            var id = $row.find("td:first").text();

            if (id.indexOf(value) !== 0) {
                $row.hide();
            }
            else {
                $row.show();
            }
        }
    });
});
</script>
 
<script type="text/javascript">
	$(document).ready(function () {
 	$("#1").show();
 	$("#2").hide();
    $("#3").hide();
$("li.home").click(function () {
    $("#1").show();
    $("#2").hide();
    $("#3").hide();
});

$("li.overview").click(function () {
    $("#2").show();
    $("#1").hide();
    $("#3").hide();
});
$("li.reports").click(function () {
    $("#2").hide();
    $("#1").hide();
    $("#3").show();
});
    });



</script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            
                var grid = document.getElementById("data");
                var rows = grid.getElementsByTagName("tr");
                var amount = 0;
                for (var i = 1; i < rows.length; i++) {
                    var cells = rows[i].getElementsByTagName("td");
                    amount += parseFloat(cells[5].innerHTML);
                }
                $('[id*=txtSum]').val(amount);
            });
    
    </script>
</body>
</html>


{% endblock %}

RCF/templates/contact.html
<style type="text/css">
	
	@import "https://fonts.googleapis.com/css?family=Raleway";
* { box-sizing: border-box; }
body { 
  margin: 0; 
  padding: 0; 
  background: #333;
  font-family: Raleway; 
  text-transform: uppercase; 
  font-size: 11px; 
}
h1{ margin: 0; }
#contact { 
  -webkit-user-select: none; /* Chrome/Safari */        
  -moz-user-select: none; /* Firefox */
  -ms-user-select: none; /* IE10+ */
  margin: 4em auto;
  width: 100px; 
  height: 30px; 
  line-height: 30px;
  background: teal;
  color: white;
  font-weight: 700;
  text-align: center;
  cursor: pointer;
  border: 1px solid white;
}

#contact:hover { background: #666; }
#contact:active { background: #444; }

#contactForm { 
  display: none;

  border: 6px solid salmon; 
  padding: 2em;
  width: 400px;
  text-align: center;
  background: #fff;
  position: fixed;
  top:50%;
  left:50%;
  transform: translate(-50%,-50%);
  -webkit-transform: translate(-50%,-50%)
  
}

input, textarea { 
  margin: .8em auto;
  font-family: inherit; 
  text-transform: inherit; 
  font-size: inherit;
  
  display: block; 
  width: 280px; 
  padding: .4em;
}
textarea { height: 80px; resize: none; }

.formBtn { 
  width: 140px;
  display: inline-block;
  
  background: teal;
  color: #fff;
  font-weight: 100;
  font-size: 1.2em;
  border: none;
  height: 30px;
}
</style>
<div id="contact">Contact</div>

<div id="contactForm">

  <h1>Keep in touch!</h1>
  <small>I'll get back to you as quickly as possible</small>
  
  <form action="#">
    <input placeholder="Name" type="text" required />
    <input placeholder="Email" type="email" required />
    <input placeholder="Subject" type="text" required />
    <textarea placeholder="Comment"></textarea>
    <input class="formBtn" type="submit" />
    <input class="formBtn" type="reset" />
  </form>
</div>

RCF/templates/myadmin.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Chapati Roti Factory Admin</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script>
	
</script>
<style>
  
    
</style>
</head>
<body>
<form method="POST" id="add_form" action="{% url 'loginpage' %}">{% csrf_token %}
    
    <div class="container">
        Username:
                <input type="text" name="login" value="" placeholder="Username" class="form-control" id="login" maxlength="80" size="30">
            <br />
                Password:
                <input type="password" name="password" value="" placeholder="Password" class="form-control" id="password" size="30">
                <br />
        <input type="submit" name="submit" value="submit" />
    </div>
    </form>
    
    

</body>
</html>                            

RCF/templates/ordernow.html
{% extends 'base.html' %}

{% block content %}

<h2>Order now Section</h2>

{% endblock %}

RCF/templates/show.html
{% extends 'base.html' %}



{% block content %}


<h1>Hello</h1>

{% endblock %}